Testing:
- Test/*
Agent:
-src/Agent/**
Env:
- src/Base/**/_env.py
Graphics:
- src/Base/**/env.py
- src/Base/**/_render_func.py
System:
- '*.py'
- Log/**
- .github/**
Document:
- '**/*.md'
- '**/*.txt'
- '**/*.docs'
